[package]
name = "riplika-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "riplika-gui"
path = "src/main.rs"

[dependencies]
riplika-core.workspace = true
gtk = { package = "gtk4", version = "0.10", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.8", features = ["v1_5"] }
gettext-rs = { version = "0.8.0", features = ["gettext-system"] }
