[package]
name = "ripper-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ripper-gui"
path = "src/main.rs"

[dependencies]
ripper-core.workspace = true
gtk = { package = "gtk4", version = "0.10", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.8", features = ["v1_5"] }
