#!/bin/sh
# Regenerate the template from the source, and refresh every catalogue from it.
#
# Run after adding or changing a string a person reads. The template is derived,
# so it is not edited by hand; the catalogues are merged rather than replaced,
# so existing translations survive a change elsewhere in the file.
set -eu
cd "$(dirname "$0")/.."

# Rust support arrived late in gettext, and the error without it names the
# language rather than the tool.
if ! printf 'fn main() {}\n' > /tmp/riplika-probe.rs \
   || ! xgettext --language=Rust -o /dev/null /tmp/riplika-probe.rs 2>/dev/null; then
  echo "this xgettext ($(xgettext --version | head -1)) does not know Rust." >&2
  echo "po/check.py checks the catalogues without it; regenerating needs a newer gettext." >&2
  rm -f /tmp/riplika-probe.rs
  exit 1
fi
rm -f /tmp/riplika-probe.rs

xgettext --files-from=po/POTFILES.in --directory=. \
  --keyword=tr --keyword=tr_n:1,2 --keyword=tr_args --language=Rust --from-code=UTF-8 --add-comments \
  --package-name=Riplika --package-version=0.2.0 \
  --copyright-holder="Niklas Rosenqvist" \
  --msgid-bugs-address="https://github.com/nsrosenqvist/riplika/issues" \
  -o po/riplika.pot
xgettext --language=Desktop --join-existing --omit-header \
  -o po/riplika.pot data/com.nsrosenqvist.Riplika.desktop

while read -r lang; do
  [ -n "$lang" ] || continue
  if [ "$lang" = "en" ]; then
    # English is not translated, it is the source. Filling it from the template
    # keeps it complete by construction - which is the whole point of shipping
    # it, since a missing catalogue is invisible in English and only English.
    msgen po/riplika.pot -o "po/$lang.po.tmp"
    # msgen copies the template's header as-is, placeholders included, and a
    # catalogue with nplurals=INTEGER does not compile.
    sed -e 's/^"Language: .*$/"Language: en\\n"/' \
        -e 's/^"Plural-Forms: .*$/"Plural-Forms: nplurals=2; plural=(n != 1);\\n"/' \
        -e 's/^"Content-Type: text\/plain; charset=ASCII/"Content-Type: text\/plain; charset=UTF-8/' \
        -e 's/^"Last-Translator: .*$/"Last-Translator: source strings <https:\/\/github.com\/nsrosenqvist\/riplika>\\n"/' \
        -e 's/^"Language-Team: .*$/"Language-Team: English\\n"/' \
        -e 's/^"PO-Revision-Date: .*$/"PO-Revision-Date: generated by po\/build.sh\\n"/' \
        "po/$lang.po.tmp" > "po/$lang.po"
    rm -f "po/$lang.po.tmp"
  elif [ -f "po/$lang.po" ]; then
    msgmerge --update --backup=none --quiet "po/$lang.po" po/riplika.pot
  else
    msginit --no-translator --locale="$lang" --input=po/riplika.pot --output-file="po/$lang.po"
  fi
  msgfmt --check --statistics "po/$lang.po" -o /dev/null
done < po/LINGUAS
